# Generated by Django 4.2.15 on 2025-06-12 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_optionsgroup_perspective_questiontype_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers_created",
                to="projects.member",
            ),
        ),
    ]
